# Generated by Django 6.1.1 on 2026-09-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('member_count', models.IntegerField(blank=True, null=True)),
                ('ticket_count', models.IntegerField(blank=True, null=True)),
                ('task_to_do_count', models.IntegerField(blank=True, null=True)),
                ('tasks_high_prio_count', models.IntegerField(blank=True, null=True)),
                ('owner_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
